### ISSUE TITLE
No parameterless constructor defined for this object.

### ISSUE THREAD

**Issue by xbrady** [polenter/SharpSerializer#1]
When I try to deserialize a complex object I'm getting the following error:
No parameterless constructor defined for this object.

I obviously have a class somewhere without a parameterless constructor, the problem is I don't know which one. Can this please be updated to include the type that it is failing to create?
Call stack:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)

**Comment by gashupl** [comment]
Had the same error. Not sure why it is happening becuase the list of objects I'm trying to deserialize may be created with parameterless constructor. Also the objects inside the list may be created using the constructor without parameters. More detailed information inside the error message would be really appreciated.

**Comment by Meekohi** [comment]
I'm getting this error on an extremely simple object that clearly has a parameterless constructor... I'm lost as to what the issue is, not sure this library actually works anymore.

**Comment by technyon** [comment]
I had the exact same issue. I proceeded to checkout the source code and directly include it in my (.NET 8) solution, and referenced it it the relevant project. The problem just went away on it's own. 

Either 
- it has been already been fixed in the meantime, but no new release has been pushed to nuget, or
- some incompatibilities between the .NET version used for compiling for nuget and my .NET version cause this problem

Either way, if you want to fix this problem, just directly include the sources in your solution/project.
